schema_version: 1
name: sso.config.launch.setup.73
version: '1.0'
description: Module to define the configuration and the form of the launch script specific to the RH-SSO 7.3 version.

modules:
  install:
  - name: os-eap-launch
  - name: os-eap7-launch
  - name: os-partition
  - name: os-eap-migration

packages:
      repositories:
          - jboss-os
      install:
          - openssl

execute:
- script: configure.sh

run:
      user: 185
      cmd:
          - "/opt/eap/bin/openshift-launch.sh"

envs:
    - name: "SERVICE_WAIT_NAME"
      example: "sso-mysql"
      description: "Name of the OpenShift service, the RH-SSO pod should wait for to become reachable over network, prior starting the RH-SSO server. Not set by default."
    - name: "SERVICE_WAIT_RETRY_MESSAGE"
      example: "Waiting for the \"${SERVICE_WAIT_NAME}\" service to become reachable over network ..."
      description: "Message to be displayed in connect-retry loop, in which the RH-SSO pod is waiting for the SERVICE_WAIT_NAME to become reachable over network. Defaults to 'Waiting for the \"${SERVICE_WAIT_NAME}\" service to become available ....' if the SERVICE_WAIT_NAME variable is set."
    - name: "SERVICE_WAIT_INTRO_MESSAGE"
      example: "Ensure a persistent volume is available for the \"${APPLICATION_NAME}-mysql-claim\" or a storage class is set."
      description: "Message to be displayed prior starting the connect-retry loop, in which the RH-SSO pod is waiting for the SERVICE_WAIT_NAME to become reachable over network. Typically describes additional requirements in order the connect-retry loop of the RH-SSO pod successfully to finish. Not set by default."
    - name: "SSO_ADMIN_USERNAME"
      example: "admin"
      description: "Username of the administrator account for the 'master' realm of the RH-SSO server. Required. If no value is specified, it is auto generated and displayed as an OpenShift Instructional message when the template is instantiated."
    - name: "SSO_ADMIN_PASSWORD"
      example: "hardtoguess"
      description: "Password of the administrator account for the 'master' realm of the RH-SSO server. Required. If no value is specified, it is auto generated and displayed as an OpenShift Instructional message when the template is instantiated."
    - name: "SSO_SERVICE_USERNAME"
      example: "username"
      description: "RH-SSO Server service username with rights to create Client configurations in SSO_REALM. This user is created if this ENV is provided"
    - name: "SSO_SERVICE_PASSWORD"
      example: "password"
      description: "Password for SSO_SERVICE_USERNAME"
