#!/usr/bin/env bash

set -eu

# Copy the TLS certificate & key generated by the OpenShift's service serving
# certificate secrets from "/etc/pki/postgresql" (which is mounted read-only,
# since coming from secret) to "/var/run/postgresql/pki", so it's possible to
# correct the permissions of the TLS private key as required below
SOURCE_DIR="/etc/pki/postgresql"
DESTINATION_DIR="/var/run/postgresql/pki"
if [ ! -d "${DESTINATION_DIR}" ]; then
  mkdir -p "${DESTINATION_DIR}"
fi
cp "${SOURCE_DIR}"/tls.{crt,key} "${DESTINATION_DIR}"

# PostgreSQL will fail to start and throw an error like:
#
#   FATAL:  private key file "/path/to/key" has group or world access
#   File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root.
#
# if the permissions of the TLS private key are incorrect.
#
# Thus correct the permissions so PostgreSQL server can start successfully
chmod 0600 "${DESTINATION_DIR}/tls.key"
