#!/usr/bin/env bash

set -eu

# About:
#
# Helper script to generate OpenShift templates for Red Hat Single Sign-On 7.5
# container image using non-default IBM Semeru 11 Open Edition JDK. It can:
#
# * Either modify the default RH-SSO templates to start using the newly created
#   "sso75-openshift-rhel8-ibm-semeru-11-jdk" image stream,
#
# * Or keep the default RH-SSO templates unchanged, and for each of them
#   generate a counterpart IBM Semeru 11 Open Edition JDK specific template
#   with custom name depending on specified TEMPLATE_SUFFIX environment
#   variable
#
# Run the script without arguments for additional usage details


# Define constants to hold the default (original) and the new image stream
# name for the RH-SSO templates
readonly ORIGINAL_RH_SSO_IMAGE_STREAM_AND_TAG="sso75-openshift-rhel8:7.5"
readonly UPDATED_RH_SSO_IMAGE_STREAM_AND_TAG="sso75-openshift-rhel8-ibm-semeru-11-jdk:latest"

# Describe the two possible ways of using template suffix
# shellcheck disable=SC2155
readonly TEMPLATE_SUFFIX_HEREDOC=$(cat << EOTSHD
  TEMPLATE_SUFFIX variable is not set. Please set it to:

  a) The empty string, if you want to start using the default RH-SSO templates
     with the new "sso75-openshift-rhel8-ibm-semeru-11-jdk" image stream:

     $ TEMPLATE_SUFFIX="" $0

     In this case each of the installed default RH-SSO templates will be
     modified to start using the new "sso75-openshift-rhel8-ibm-semeru-11-jdk"
     image stream.

  b) The desired string, if you want to derive new OpenShift templates for the
     "sso75-openshift-rhel8-ibm-semeru-11-jdk" image stream from the default
     RH-SSO templates. For example:

     $ TEMPLATE_SUFFIX="-ibm-semeru-11-jdk" $0

     In this case the default RH-SSO templates will remain unchanged. Instead
     for each of the installed default RH-SSO templates, a new template with a
     name of '<original-template><template-suffix>' will be created for the
     "sso75-openshift-rhel8-ibm-semeru-11-jdk" image stream.

     For example, for TEMPLATE_SUFFIX matching "-ibm-semeru-11-jdk" the
     counterpart IBM Semeru 11 JDK template of the default "sso75-x509-https"
     RH-SSO template will have the name of "sso75-x509-https-ibm-semeru-11-jdk"
     etc.
EOTSHD
)

# TEMPLATE_SUFFIX environment variable has to be set. If not, that's an error
if [ -z "${TEMPLATE_SUFFIX+set}" ]
then
  echo -e "\n${TEMPLATE_SUFFIX_HEREDOC}\n"
  exit 1
fi

# Ensure OpenShift CLI (oc) tool is installed. If not, that's en error
if ! oc version --client >& /dev/null
then
  # shellcheck disable=SC2155
  readonly ocErrorMessage=$(cat << EOOCEM
  Please ensure you have the OpenShift CLI (oc) tool installed:
  * https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html#installing-openshift-cli
EOOCEM
)
  echo -e "\n${ocErrorMessage}\n"
  exit 1
fi

# Ensure the user is logged in
if ! oc whoami >& /dev/null
then
  # shellcheck disable=SC2155
  readonly ocLoginRequiredMessage=$(cat << EOOCLRM
  Please log in as a cluster administrator or a user with project administrator access to the global "openshift" project.
EOOCLRM
)
  echo -e "\n${ocLoginRequiredMessage}\n"
  exit 1
fi

# Array of all RH-SSO templates existing in the OpenShift cluster. It's a sum
# of the default ones together with those generated by previous runs of this
# script
mapfile -t ALL_RH_SSO_TEMPLATES< <(
  oc get templates -n openshift | grep sso75 | cut -d ' ' -f 1
)
# Such array has to be non-empty. If not, that's an error
if [ "${#ALL_RH_SSO_TEMPLATES[@]}" -eq "0" ]
then
  echo "Please install the standard OpenShift RH-SSO image templates first."
  exit 1
fi

# Array of various template suffixes specified by previous runs of the script
#
# Since there can be multiple existing template suffixes thanks to multiple
# previous runs of the script using the different suffix, identify these
# suffixes by filtering all the templates for one specific default template
# name and subsequently removing this default template name from them
# shellcheck disable=SC2207
declare -a PREVIOUSLY_USED_TEMPLATE_SUFFIXES=(
  $(
    echo "${ALL_RH_SSO_TEMPLATES[*]}" | tr $' ' $'\n' |
    grep -P '^sso75-x509-https' | grep -Pv '^$' |
    sed -e 's/^sso75-x509-https//g'
  )
)

# Array of default RH-SSO template names is a subset of all RH-SSO templates
declare -a DEFAULT_RH_SSO_TEMPLATES=( "${ALL_RH_SSO_TEMPLATES[@]}" )
# Except those containing some of previously used suffixes in their name
for previousSuffix in "${PREVIOUSLY_USED_TEMPLATE_SUFFIXES[@]}"
do
  # Globbing is actually intentional in the following statement
  # shellcheck disable=SC2206
  DEFAULT_RH_SSO_TEMPLATES=(
    ${DEFAULT_RH_SSO_TEMPLATES[@]/*${previousSuffix}/}
  )
done

# Generate the RH-SSO templates for the latest release of IBM Semeru 11 JDK
# Open Edition based on specified template suffix -- either overwrite the
# default ones, or generate new ones with custom names
for tmplName in "${DEFAULT_RH_SSO_TEMPLATES[@]}"
do
  SEMERU_TEMPLATE_PATH="/tmp/${tmplName}${TEMPLATE_SUFFIX}.json"
  # Get the code of particular template in JSON format
  oc get template "${tmplName}" -n openshift -o json > "${SEMERU_TEMPLATE_PATH}"
  # Update template name within template code
  sed -i "s/${tmplName}/${tmplName}${TEMPLATE_SUFFIX}/g" "${SEMERU_TEMPLATE_PATH}"
  # Update image stream name and tag within template code
  sed -i "s/${ORIGINAL_RH_SSO_IMAGE_STREAM_AND_TAG}/${UPDATED_RH_SSO_IMAGE_STREAM_AND_TAG}/g" "${SEMERU_TEMPLATE_PATH}"
  # Recreate the updated template with template suffix in global 'openshift' project
  oc replace --force -f "${SEMERU_TEMPLATE_PATH}"
  # Remove the intermediary template file
  rm -f "${SEMERU_TEMPLATE_PATH}"
done
