#!/bin/sh
# ==============================================================================
# JDK specific customizations
#
# ==============================================================================

# Remove the following function with OpenJ9 0.18.0 is available. See JBEAP-17984
function jvm_specific_options() {
    if [[ $(uname -i) = s390x ]] ; then
        echo "-Xmx2g"
    else
        :
    fi
}

function jvm_specific_diagnostics() {
    if [[ $(uname -i) = s390x ]] ; then
        echo ""
    else
        echo "-XX:NativeMemoryTracking=summary -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UnlockDiagnosticVMOptions"
    fi
}
